import type { Course, Opportunity } from "./types";

/**
 * High-fidelity mock data. In production these rows live in Postgres/Supabase
 * and are managed through the Admin Suite — the shape below mirrors that schema.
 */

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "nasa-space-apps",
    title: "NASA Space Apps Challenge — Almaty",
    organizer: "NASA / Astana Hub",
    type: "Hackathon",
    direction: "STEM",
    format: "Hybrid",
    location: "Almaty, Kazakhstan",
    deadline: "2026-09-28",
    grades: [9, 10, 11],
    description:
      "The world's largest annual space hackathon. Teams use open NASA data to build apps tackling real challenges on Earth and in space across a 48-hour sprint.",
    eligibility: "Students 14+ in teams of 2–6. No prior coding required for all tracks.",
    prize: "Global nomination + mentorship",
    tags: ["space", "data", "teamwork", "coding"],
    applyUrl: "https://www.spaceappschallenge.org",
  },
  {
    id: "econ-republican-olympiad",
    title: "Republican Olympiad in Economics",
    organizer: "Ministry of Education RK",
    type: "Olympiad",
    direction: "Finance",
    format: "In-person",
    location: "Astana, Kazakhstan",
    deadline: "2026-07-05",
    grades: [10, 11],
    description:
      "National-level economics olympiad covering microeconomics, macroeconomics and financial literacy. Winners receive Altyn Belgi consideration and university grants.",
    eligibility: "Grades 10–11, top-3 placement at regional round.",
    prize: "University grant (grant-on-budget)",
    tags: ["economics", "finance", "national", "scholarship"],
    applyUrl: "https://example.org/econ-olympiad",
  },
  {
    id: "stanford-humanities",
    title: "Stanford Summer Humanities Institute",
    organizer: "Stanford University",
    type: "Summer School",
    direction: "Humanities",
    format: "In-person",
    location: "Stanford, USA",
    deadline: "2026-07-19",
    grades: [10, 11],
    description:
      "A pre-collegiate residential program where students explore big questions in history, philosophy and literature alongside Stanford professors and PhD mentors.",
    eligibility: "Sophomores & juniors with strong writing samples. Need-based aid available.",
    prize: "Stanford transcript credit",
    tags: ["writing", "philosophy", "history", "residential"],
    applyUrl: "https://summerhumanities.spcs.stanford.edu",
  },
  {
    id: "wharton-investment",
    title: "Wharton Global High School Investment Competition",
    organizer: "Wharton, UPenn",
    type: "Competition",
    direction: "Business",
    format: "Online",
    location: "Global (Online)",
    deadline: "2026-06-29",
    grades: [9, 10, 11],
    description:
      "Teams act as financial advisors, building a real strategy for a virtual client and managing a simulated portfolio. The flagship business competition for high schoolers.",
    eligibility: "Teams of 4–7 + 1 advisor (teacher/mentor). Open worldwide.",
    prize: "Global Finale at Wharton",
    tags: ["investing", "business", "finance", "teamwork"],
    applyUrl: "https://globalyouth.wharton.upenn.edu",
  },
  {
    id: "google-csb",
    title: "Google Code-in & CS Bridge",
    organizer: "Google for Education",
    type: "Internship",
    direction: "Programming",
    format: "Online",
    location: "Global (Online)",
    deadline: "2026-08-15",
    grades: [9, 10, 11],
    description:
      "A guided open-source contribution program introducing students to real software engineering workflows, code review, and collaboration with mentors at top orgs.",
    eligibility: "Ages 13–18. Basic programming familiarity recommended.",
    prize: "Certificate + swag + mentor letter",
    tags: ["open-source", "coding", "mentorship", "github"],
    applyUrl: "https://codein.withgoogle.com",
  },
  {
    id: "ibo-biology",
    title: "International Biology Olympiad (IBO) Prep Track",
    organizer: "IBO Committee",
    type: "Olympiad",
    direction: "Science",
    format: "Hybrid",
    location: "Yerevan, Armenia",
    deadline: "2026-10-10",
    grades: [10, 11],
    description:
      "Selective preparation and qualifying rounds for the International Biology Olympiad, covering cell biology, genetics, ecology and lab practicals.",
    eligibility: "Grades 10–11 with strong biology background.",
    prize: "National team selection",
    tags: ["biology", "genetics", "lab", "international"],
    applyUrl: "https://www.ibo-info.org",
  },
  {
    id: "unicef-youth",
    title: "UNICEF Youth Social Impact Fellowship",
    organizer: "UNICEF Kazakhstan",
    type: "Volunteering",
    direction: "Social Impact",
    format: "Hybrid",
    location: "Almaty / Online",
    deadline: "2026-07-31",
    grades: [9, 10, 11],
    description:
      "A 3-month fellowship empowering teens to design and launch community projects addressing local SDG challenges, with stipends and a network of changemakers.",
    eligibility: "Ages 14–18 passionate about social change. Motivation letter required.",
    prize: "Micro-grant up to $500",
    tags: ["sdg", "community", "leadership", "volunteering"],
    applyUrl: "https://example.org/unicef-youth",
  },
  {
    id: "mit-launchx",
    title: "MIT LaunchX Entrepreneurship Program",
    organizer: "MIT LaunchX",
    type: "Summer School",
    direction: "Business",
    format: "Online",
    location: "Global (Online)",
    deadline: "2026-08-01",
    grades: [10, 11],
    description:
      "An intensive program where students launch a real startup — from customer discovery to MVP and a live pitch to investors — guided by MIT entrepreneurs.",
    eligibility: "Motivated students 14–18. Selective application.",
    prize: "Investor demo day",
    tags: ["startup", "entrepreneurship", "pitch", "business"],
    applyUrl: "https://launchx.com",
  },
  {
    id: "qbiz-research",
    title: "Quantum Computing Research Mentorship",
    organizer: "Nazarbayev University Lab",
    type: "Research",
    direction: "STEM",
    format: "Hybrid",
    location: "Astana, Kazakhstan",
    deadline: "2026-09-05",
    grades: [11],
    description:
      "Pair with a graduate researcher on an introductory quantum information project and co-author a short research note suitable for science fairs.",
    eligibility: "Grade 11 with strong math/physics. Application + interview.",
    prize: "Research note + recommendation letter",
    tags: ["physics", "research", "quantum", "math"],
    applyUrl: "https://example.org/qbiz-research",
  },
  {
    id: "ielts-scholar",
    title: "Mentoria IELTS Excellence Scholarship",
    organizer: "Mentoria",
    type: "Scholarship",
    direction: "Humanities",
    format: "Online",
    location: "Global (Online)",
    deadline: "2026-06-24",
    grades: [9, 10, 11],
    description:
      "Full scholarship covering an IELTS exam fee and a structured prep course for students who demonstrate financial need and academic motivation.",
    eligibility: "Grades 9–11. Short essay + practice test score.",
    prize: "Covered exam fee + prep course",
    tags: ["ielts", "english", "scholarship", "exam"],
    applyUrl: "https://example.org/ielts-scholar",
  },
  {
    id: "f1-in-schools",
    title: "F1 in Schools — STEM Racing Challenge",
    organizer: "F1 in Schools",
    type: "Competition",
    direction: "Programming",
    format: "Hybrid",
    location: "Regional Hubs",
    deadline: "2026-11-20",
    grades: [8, 9, 10, 11],
    description:
      "Design, CAD-model and 3D-print a miniature F1 car, manage a team budget and race it — blending engineering, marketing and project management.",
    eligibility: "Teams of 3–6, grades 8–11.",
    prize: "National finals berth",
    tags: ["engineering", "cad", "design", "teamwork"],
    applyUrl: "https://www.f1inschools.com",
  },
  {
    id: "hsdc-debate",
    title: "Harvard Schools Debating Championship",
    organizer: "Harvard Debate Council",
    type: "Competition",
    direction: "Humanities",
    format: "In-person",
    location: "Cambridge, USA",
    deadline: "2026-08-30",
    grades: [9, 10, 11],
    description:
      "A premier World Schools format debate tournament building argumentation, public speaking and critical-thinking skills on global affairs.",
    eligibility: "Grades 9–11. Team or independent registration.",
    prize: "International ranking points",
    tags: ["debate", "speaking", "critical-thinking", "english"],
    applyUrl: "https://example.org/harvard-debate",
  },
];

export const COURSES: Course[] = [
  {
    id: "intro-economics",
    title: "Introduction to Economics",
    subject: "Economics",
    level: "Beginner",
    direction: "Finance",
    description:
      "Build economic intuition from scratch — scarcity, markets, incentives and how money moves through an economy. Perfect for olympiad and admissions prep.",
    instructor: "Dr. Aizhan Serik",
    hours: 6,
    accent: "from-emerald-500 to-teal-600",
    tags: ["economics", "finance", "business"],
    lessons: [
      {
        id: "econ-l1",
        title: "Scarcity & Opportunity Cost",
        duration: "12 min",
        videoLabel: "Lesson 1 · The core economic problem",
        notes: [
          "**Scarcity** means unlimited wants meet limited resources — the root of every economic decision.",
          "**Opportunity cost** is the value of the next-best alternative you give up.",
          "Rational agents weigh marginal benefit against marginal cost.",
          "Example: studying an extra hour for SAT vs. resting before the exam.",
        ],
        resources: [
          { label: "Reading: Mankiw Ch.1 summary", href: "#" },
          { label: "Worksheet: Trade-off matrix", href: "#" },
        ],
        quiz: [
          {
            q: "What does 'opportunity cost' represent?",
            options: [
              "The money you spent",
              "The value of the next-best option forgone",
              "The total resources available",
              "A government tax",
            ],
            answer: 1,
            explain: "Opportunity cost = the best alternative you gave up.",
          },
          {
            q: "Scarcity exists because…",
            options: [
              "People are lazy",
              "Wants are unlimited but resources are limited",
              "Money is printed slowly",
              "Markets are unfair",
            ],
            answer: 1,
          },
          {
            q: "A rational agent makes a choice when…",
            options: [
              "The marginal benefit exceeds the marginal cost",
              "The product is free",
              "Everyone else is doing it",
              "There is no opportunity cost",
            ],
            answer: 0,
            explain: "Decisions are made at the margin: benefit > cost.",
          },
        ],
      },
      {
        id: "econ-l2",
        title: "Supply, Demand & Market Equilibrium",
        duration: "16 min",
        videoLabel: "Lesson 2 · How prices are discovered",
        notes: [
          "**Demand** slopes down: as price falls, quantity demanded rises.",
          "**Supply** slopes up: higher prices motivate more production.",
          "**Equilibrium** is where supply meets demand — the market-clearing price.",
          "Shifts vs. movements: a price change moves along the curve; other factors shift it.",
        ],
        resources: [
          { label: "Interactive: Supply-demand simulator", href: "#" },
          { label: "Cheat sheet: 5 demand shifters", href: "#" },
        ],
        quiz: [
          {
            q: "At market equilibrium…",
            options: [
              "Supply exceeds demand",
              "Quantity supplied equals quantity demanded",
              "Prices always rise",
              "There is a shortage",
            ],
            answer: 1,
          },
          {
            q: "A new health study makes a fruit popular. The demand curve…",
            options: ["Shifts left", "Shifts right", "Stays still", "Becomes vertical"],
            answer: 1,
            explain: "More desire at every price → rightward shift.",
          },
          {
            q: "If price is set ABOVE equilibrium, the result is a…",
            options: ["Shortage", "Surplus", "Perfect balance", "Higher demand"],
            answer: 1,
            explain: "Above equilibrium, quantity supplied exceeds demand → surplus.",
          },
        ],
      },
      {
        id: "econ-l3",
        title: "Inflation & the Role of Central Banks",
        duration: "14 min",
        videoLabel: "Lesson 3 · Money, prices and policy",
        notes: [
          "**Inflation** is a sustained rise in the general price level.",
          "Central banks (like the National Bank of Kazakhstan) use interest rates to steer it.",
          "Higher rates cool spending; lower rates stimulate it.",
          "Real value = nominal value adjusted for inflation.",
        ],
        resources: [{ label: "Data: KZ inflation 2015–2025", href: "#" }],
        quiz: [
          {
            q: "To reduce high inflation a central bank typically…",
            options: [
              "Lowers interest rates",
              "Raises interest rates",
              "Prints more money",
              "Bans saving",
            ],
            answer: 1,
          },
          {
            q: "Inflation is best defined as…",
            options: [
              "A one-time price jump",
              "A sustained rise in the general price level",
              "A fall in wages",
              "An increase in taxes",
            ],
            answer: 1,
          },
          {
            q: "'Real' value differs from 'nominal' value because real value is…",
            options: [
              "Adjusted for inflation",
              "Always larger",
              "Set by the government",
              "Measured in dollars only",
            ],
            answer: 0,
          },
        ],
      },
    ],
  },
  {
    id: "sat-math",
    title: "SAT Math Mastery",
    subject: "Mathematics",
    level: "Intermediate",
    direction: "STEM",
    description:
      "A focused sprint through the highest-yield SAT math topics with exam strategy, timing drills and instant-feedback practice to lift your score fast.",
    instructor: "Timur Bekov, 1580 SAT",
    hours: 8,
    accent: "from-indigo-500 to-violet-600",
    tags: ["sat", "math", "exam", "admission"],
    lessons: [
      {
        id: "sat-l1",
        title: "Heart of Algebra: Linear Equations",
        duration: "15 min",
        videoLabel: "Lesson 1 · Lines, slopes & systems",
        notes: [
          "Master slope-intercept form **y = mx + b**.",
          "Slope = rise / run; parallel lines share slope, perpendicular slopes multiply to −1.",
          "Solve systems by substitution or elimination — pick the faster one.",
          "Translate word problems into equations *before* computing.",
        ],
        resources: [
          { label: "Drill set: 20 linear problems", href: "#" },
          { label: "Formula sheet (printable)", href: "#" },
        ],
        quiz: [
          {
            q: "The slope of the line through (1,2) and (3,8) is:",
            options: ["2", "3", "4", "6"],
            answer: 1,
            explain: "(8−2)/(3−1) = 6/2 = 3.",
          },
          {
            q: "Perpendicular lines have slopes that…",
            options: [
              "Are equal",
              "Add to 0",
              "Multiply to −1",
              "Are both positive",
            ],
            answer: 2,
          },
          {
            q: "In y = mx + b, the value b represents the…",
            options: ["Slope", "y-intercept", "x-intercept", "Vertex"],
            answer: 1,
            explain: "b is where the line crosses the y-axis.",
          },
        ],
      },
      {
        id: "sat-l2",
        title: "Problem Solving & Data Analysis",
        duration: "18 min",
        videoLabel: "Lesson 2 · Ratios, percent & graphs",
        notes: [
          "Percent change = (new − old) / old × 100.",
          "Set up ratios as fractions and cross-multiply.",
          "Read every axis label and unit before answering a graph question.",
          "Watch for 'percent of' vs 'percent more than' traps.",
        ],
        resources: [{ label: "Practice: 15 data questions", href: "#" }],
        quiz: [
          {
            q: "A $80 item rises to $100. The percent increase is:",
            options: ["20%", "25%", "80%", "120%"],
            answer: 1,
            explain: "(100−80)/80 = 0.25 = 25%.",
          },
          {
            q: "If 3 pens cost 150₸, 7 pens cost:",
            options: ["300₸", "350₸", "450₸", "210₸"],
            answer: 1,
            explain: "50₸ each × 7 = 350₸.",
          },
          {
            q: "A price drops from $50 to $40. The percent decrease is:",
            options: ["10%", "20%", "25%", "40%"],
            answer: 1,
            explain: "(50−40)/50 = 0.20 = 20%.",
          },
        ],
      },
      {
        id: "sat-l3",
        title: "Passport to Advanced Math",
        duration: "20 min",
        videoLabel: "Lesson 3 · Quadratics & functions",
        notes: [
          "Factor quadratics or use the quadratic formula when factoring is hard.",
          "The vertex of y = a(x−h)² + k is (h, k).",
          "Function notation: f(g(x)) means apply g first, then f.",
          "Discriminant b²−4ac tells you how many real roots exist.",
        ],
        resources: [{ label: "Mixed quadratics drill", href: "#" }],
        quiz: [
          {
            q: "How many real roots does x² + 1 = 0 have?",
            options: ["0", "1", "2", "Infinite"],
            answer: 0,
            explain: "Discriminant = −4 < 0 → no real roots.",
          },
          {
            q: "The vertex of y = (x − 3)² + 2 is at:",
            options: ["(3, 2)", "(−3, 2)", "(2, 3)", "(3, −2)"],
            answer: 0,
            explain: "For a(x−h)²+k the vertex is (h, k) = (3, 2).",
          },
          {
            q: "If f(x) = x + 1 and g(x) = 2x, then f(g(2)) =",
            options: ["4", "5", "6", "3"],
            answer: 1,
            explain: "g(2)=4, then f(4)=5.",
          },
        ],
      },
    ],
  },
  {
    id: "academic-english",
    title: "Academic English for University Prep",
    subject: "English",
    level: "Beginner",
    direction: "Humanities",
    description:
      "Write and speak with academic confidence. Covers essay structure, the IELTS writing task, and the vocabulary admissions officers love to see.",
    instructor: "Sarah Coleman, IELTS 9.0",
    hours: 7,
    accent: "from-rose-500 to-orange-500",
    tags: ["english", "ielts", "writing", "admission"],
    lessons: [
      {
        id: "eng-l1",
        title: "The Anatomy of an Academic Essay",
        duration: "13 min",
        videoLabel: "Lesson 1 · Structure that scores",
        notes: [
          "Every essay = Introduction → Body paragraphs → Conclusion.",
          "A strong **thesis** states your position in one clear sentence.",
          "Use the PEEL pattern: Point, Evidence, Explain, Link.",
          "Cohesion words (however, moreover, consequently) guide the reader.",
        ],
        resources: [
          { label: "Template: 4-paragraph essay", href: "#" },
          { label: "50 academic linking words", href: "#" },
        ],
        quiz: [
          {
            q: "Where does the thesis statement usually appear?",
            options: [
              "In the conclusion",
              "End of the introduction",
              "In every paragraph",
              "It is optional",
            ],
            answer: 1,
          },
          {
            q: "PEEL stands for Point, Evidence, Explain and…",
            options: ["Leave", "Link", "List", "Learn"],
            answer: 1,
          },
          {
            q: "Which word best signals a contrast between ideas?",
            options: ["Moreover", "However", "Therefore", "Similarly"],
            answer: 1,
            explain: "'However' marks contrast; the others add or conclude.",
          },
        ],
      },
      {
        id: "eng-l2",
        title: "IELTS Writing Task 2 Strategy",
        duration: "17 min",
        videoLabel: "Lesson 2 · Opinion & discussion essays",
        notes: [
          "Spend ~5 minutes planning before you write.",
          "Answer *all* parts of the prompt — examiners check Task Response.",
          "Aim for 250+ words across 4 paragraphs.",
          "Show range: mix simple and complex sentences accurately.",
        ],
        resources: [{ label: "Band 9 sample essays", href: "#" }],
        quiz: [
          {
            q: "Minimum word count for IELTS Writing Task 2 is:",
            options: ["150", "200", "250", "400"],
            answer: 2,
          },
          {
            q: "Roughly how long should you spend planning before writing?",
            options: ["0 minutes", "~5 minutes", "20 minutes", "Half the time"],
            answer: 1,
            explain: "A quick ~5-minute plan keeps your essay focused.",
          },
          {
            q: "The examiner's 'Task Response' criterion checks whether you…",
            options: [
              "Used long words",
              "Answered all parts of the prompt",
              "Wrote quickly",
              "Used a pen",
            ],
            answer: 1,
          },
        ],
      },
      {
        id: "eng-l3",
        title: "Vocabulary for the Personal Statement",
        duration: "11 min",
        videoLabel: "Lesson 3 · Sound like a scholar",
        notes: [
          "Replace weak verbs: 'did' → 'spearheaded', 'led', 'designed'.",
          "Show, don't tell — give one vivid concrete example.",
          "Avoid clichés ('since I was a child', 'passion for helping people').",
          "Edit ruthlessly: cut 10% of your first draft.",
        ],
        resources: [{ label: "Power-verb word bank", href: "#" }],
        quiz: [
          {
            q: "Which is the strongest opening for a personal statement?",
            options: [
              "I have always been passionate about science.",
              "Since I was a child I loved learning.",
              "The petri dish glowed faint blue — my first failed experiment.",
              "I want to study at your university.",
            ],
            answer: 2,
            explain: "A concrete, specific scene shows rather than tells.",
          },
          {
            q: "Which verb is strongest on a personal statement?",
            options: ["Did", "Helped with", "Spearheaded", "Was part of"],
            answer: 2,
            explain: "Active, specific verbs like 'spearheaded' show ownership.",
          },
          {
            q: "A good editing habit for a first draft is to…",
            options: [
              "Add 10% more words",
              "Cut about 10% of the words",
              "Never change it",
              "Use more clichés",
            ],
            answer: 1,
          },
        ],
      },
    ],
  },
];
